---
# yamllint disable rule:line-length
.github/workflows/ci.yml:
  beaker_fact_matrix: {}
  excludes: []
  pidfile_workaround: false
  timeout_minutes: 40
.travis.yml:
  delete: true
Jenkinsfile:
  delete: true
Gemfile:
  puppet_version: '>= 6.0'
  required:
    ':test':
      - gem: voxpupuli-test
        version: '~> 4.0'
      - gem: coveralls
      - gem: simplecov-console
      - gem: puppet_metadata
        version: '~> 1.0'
    ':development':
      - gem: guard-rake
      - gem: overcommit
        version: '>= 0.39.1'
    ':system_tests':
      - gem: voxpupuli-acceptance
        version: '~> 1.0'
    ':release':
      - gem: github_changelog_generator
        version: '>= 1.16.1'
        ruby-version: '2.5'
        ruby-operator: '>='
      - gem: voxpupuli-release
        version: '>= 1.2.0'
      - gem: puppet-strings
        version: '>= 2.8'
Rakefile:
  config.user: voxpupuli
  puppet_strings_patterns: []
spec/default_facts.yml:
  delete: true
spec/classes/coverage_spec.rb:
  delete: true
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-511-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-6-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  delete: true
spec/acceptance/nodesets/centos-7-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-72-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-78-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-82-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-20-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-24-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-25-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-26-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-27-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2008R2-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2012-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2012R2-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: false
spec/spec_helper_acceptance.rb:
  unmanaged: true
CONTRIBUTING.md:
  delete: true
.yardopts:
  delete: true
...
# vim: syntax=yaml
