---
.github/settings.yml:
  repository:
    private: false
    has_issues: true
    has_projects: false
    has_wiki: false
    has_downloads: true
    default_branch: master
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: true
    archived: false
  branches:
    - name: master
      protection:
        required_pull_request_reviews: undef
        required_status_checks:
          strict: true
          contexts: []
        enforce_admins: undef
        restrictions: undef
        required_signatures: false
    - name: modulesync
      protection:
        required_pull_request_reviews: undef
        required_status_checks:
          strict: true
          contexts: []
        enforce_admins: undef
        restrictions: undef
        required_signatures: true
        allow_force_pushes: true
        allow_deletions: true
.travis.yml:
  before_install:
    - yes | gem update --system
    - bundle --version
  docker_sets:
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
  - rvm: 2.5.3
    services: docker
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=@@SET@@ CHECK=beaker
    bundler_args: --without development release
  - rvm: 2.5.3
    services: docker
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=@@SET@@ CHECK=beaker
    bundler_args: --without development release
  includes:
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=test
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    bundler_args: --without system_tests development release
  - rvm: 2.5.3
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    bundler_args: --without system_tests development release
  - rvm: 2.4.4
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    bundler_args: --without system_tests development release
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
    - "chat.freenode.org#voxpupuli-notifications"
  user: puppet
CODEOWNERS:
  permissions:
    '.github/settings.yml': '@voxpupuli/project-maintainers'
Gemfile:
  required:
    ':test':
      - gem: voxpupuli-test
        version: '~> 2.0'
      - gem: coveralls
      - gem: simplecov-console
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
      - gem: overcommit
        version: '>= 0.39.1'
    ':system_tests':
      - gem: voxpupuli-acceptance
    ':release':
      - gem: github_changelog_generator
        git: https://github.com/voxpupuli/github-changelog-generator
        branch: voxpupuli_essential_fixes
      - gem: puppet-blacksmith
      - gem: voxpupuli-release
      - gem: puppet-strings
        version: '>= 2.2'
Rakefile:
  config.user: voxpupuli
  puppet_strings_patterns: []
spec/default_facts.yml:
  delete: true
spec/classes/coverage_spec.rb:
  delete: true
spec/acceptance/nodesets/centos-511-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-6-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  delete: true
spec/acceptance/nodesets/centos-7-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-72-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-78-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-82-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-20-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-24-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-25-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-26-x64.yml:
  delete: true
spec/acceptance/nodesets/fedora-27-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2008R2-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2012-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/windows-2012R2-serverstandard-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: false
spec/spec_helper_acceptance.rb:
  unmanaged: true
CONTRIBUTING.md:
  delete: true
...
# vim: syntax=yaml
